language: java

matrix:
  include:
    # License, formatter, and FindBugs check
    - environment: NAME="License, formatter, and FindBugs check"
      os: linux
      sudo: false
      jdk: openjdk8
      script:
        - mvn license:check
        - mvn formatter:validate
        - mvn findbugs:check

    # Coverage report
    - environment: NAME="Coverage report"
      os: linux
      sudo: false
      jdk: openjdk8
      script:
        - mvn cobertura:cobertura
      after_success:
        - mvn coveralls:report

    # Linux tests (Java 8 LTS)
    - environment: NAME="Linux tests (Java 8)"
      os: linux
      sudo: false
      jdk: openjdk8
      script:
        - mvn test

    # Linux tests (Java 9)
    - environment: NAME="Linux tests (Java 9)"
      os: linux
      sudo: false
      jdk: openjdk9
      script:
        - mvn test

    # Linux tests (Java 10)
    - environment: NAME="Linux tests (Java 10)"
      os: linux
      sudo: false
      script:
        - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
        - source ./install-jdk.sh -F 10 -L GPL
        - mvn test

    # Linux tests (Java 11 LTS)
    - environment: NAME="Linux tests (Java 11)"
      os: linux
      sudo: false
      script:
        - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
        - source ./install-jdk.sh -F 11 -L GPL
        - mvn test

cache:
  directories:
    - $HOME/.m2
